name: note_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.6 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  date_time_picker: ^2.1.0
  flutter_local_notifications: ^11.0.0
  localstorage: ^4.0.0+1
  cron: ^0.5.1
  get: 4.6.5
  intl: ^0.17.0
  sqflite: ^2.2.2
  file_picker: 5.2.4
  uuid: 3.0.7
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: 2.0.1
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/fonts/
    - assets/images/
  fonts: 
    - family: Poppins
      fonts: 
        - asset: assets/fonts/Poppins/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins/Poppins-Medium.ttf
        - asset: assets/fonts/Poppins/Poppins-SemiBold.ttf
        - asset: assets/fonts/Poppins/Poppins-Bold.ttf
  uses-material-design: true

